### ISSUE TITLE
Preload does not work with openBalena instances using self-signed certificates

### ISSUE THREAD

**Issue by cjgordon** [balena-io/balena-preload#194]
When trying to preload and image using openBalena instance with self signed certificates I get the following error:
    
    $ balena preload balena-intel-nuc-2.29.0-v9.0.1.img --app myApp
    Building Docker preloader image. [========================] 100%
    / Creating preloader container
    | Starting preloader container
    / Fetching application gateway
    / Reading image information
    ? Select a release latest
    \ Resizing partitions and waiting for dockerd to start
    - Cleaning up temporary files
    (HTTP code 500) server error - Get https://registry.myDomain.com/v2/: x509: certificate signed by 
    unknown authority 

I believe the instance of docker daemon being spun up to preload the container images onto the image does not have the correct CA certificate configuration to trust the self-signed certificate. I have tried using the --ca and --key options but I believe these are for authenticating with docker host specified with --dockerHost not the image registry.

Cheers
Chris

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gfgr)

**Comment by zvin** [comment]
This should be fixed on Linux hosts in `v8.1.0` with https://github.com/balena-io/balena-preload/pull/195 .
Not sure how to implement this on other OSes for now.

**Comment by dfunckt** [comment]
Regarding cross-platfrom support — quoting you from that PR:

> As for passing certificates explicitly, I've found this https://docs.docker.com/engine/security/certificates/ . Implementation will be difficult. If we ask the user for a .pem, we need to extract the .crt and the domain name from it and place it into /etc/docker/certs.d/DOMAIN/ca.crt in the container.

In a later step we could potentially use openssh to find the domain name automatically but for now requiring the user to explicitly specify the cert and domain name sounds reasonable to me.

**Comment by zvin** [comment]
Use the `--add-certificate` option.
