### ISSUE TITLE
"Release not found" error when the commit value is "latest" 

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-preload#204]
A customer reported that "balena preload" stopped working and I believe I have narrowed the issue down to the use of the alias "latest" instead of a commit hash value. I believe I have further identified the issue to have been introduced by the following PR:

https://github.com/balena-io/balena-preload/pull/201/files

Because when I pinned `balena-preload` to version 8.1.1 in the CLI's `package.json`, using the "`-c latest`" option seemed to work OK.

**Comment by pdcastro** [comment]
@Page-, @zvin, does it sound plausible that the PR I linked in this issue is the cause of the "Release not found" error? Is the fix obvious to you? Thanks!

**Comment by zvin** [comment]
I think the "latest" alias is only used in the cli https://github.com/balena-io/balena-cli/blob/master/lib/actions/preload.coffee#L288-L291

**Comment by zvin** [comment]
@pdcastro you're right, the preloader can be created with "latest" here https://github.com/balena-io/balena-cli/blob/master/lib/actions/preload.coffee#L288-L291 , then `_fetchApplication` is called before this https://github.com/balena-io/balena-cli/blob/master/lib/actions/preload.coffee#L289 and the `releaseFilter` is incorrect.

**Comment by pdcastro** [comment]
A piece of data I forgot to add before: when "--commit latest" was used, `balena-preload` (or some other repo/SDK used by it) would print on the screen:
```
Release not found: 1e152b2abe0f7ba8891b32e6ba2fab2a
```
Meaning that `balena-preload` (or some other repo/SDK used by it) actually resolved "latest" to "1e152b2abe0f7ba8891b32e6ba2fab2a", yet failed.

**Comment by zvin** [comment]
We could avoid filtering by commit here https://github.com/balena-io/balena-cli/blob/master/lib/actions/preload.coffee#L289 if the commit is "latest".
Maybe there's a way to only get the latest release in that case?
cc @Page-
