### ISSUE TITLE
Rare mount error

### ISSUE THREAD

**Issue by zvin** [balena-io/balena-preload#77]
This happens rarely and restarting the script fixes it in general.
This one is with a flasher type image but I think I've already seen it with a regular image.
Not sure what to do about it.

```
Container size: 645.55 MiB
This is a flasher image, preloading into /opt/resin-image-ts4900.resinos-img on the 2nd partition of /img/resin.img
Resizing the 2nd partition of the image.
New disk image size: 4.82 GiB.
Using /dev/loop9
Resizing filesystem
e2fsck: File system OK
Expanding image size by 710.11 MiB
Expanding extended partition 4 and logical partition 6 to the end of the disk image.
Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 447, in <module>
    main()
  File "/usr/src/app/preload.py", line 440, in main
    preload(image, additional_space, app_data)
  File "/usr/src/app/preload.py", line 404, in preload
    resize_fs_copy_splash_image_and_pull(image, app_data)
  File "/usr/src/app/preload.py", line 305, in resize_fs_copy_splash_image_and_pull
    version = get_resin_os_version(image)
  File "/usr/src/app/preload.py", line 185, in get_resin_os_version
    with mount_context_manager(image, 2) as mountpoint:
  File "/usr/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 92, in mount_context_manager
    mountpoint = mount_partition(image, partition, extra_options)
  File "/usr/src/app/preload.py", line 86, in mount_partition
    mount("-o", options, image, mountpoint)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_32: 

  RAN: /bin/mount -o offset=46137344,sizelimit=327155712 /tmp/tmphaofl9n9/opt/resin-image-ts4900.resinos-img /tmp/tmpx1ukr6dl

  STDOUT:


  STDERR:
mount: /tmp/tmphaofl9n9/opt/resin-image-ts4900.resinos-img: failed to setup loop device: No such file or directory


[ERROR] Preloader exited with code 1

```

**Comment by jhermsmeier** [comment]
`Using /dev/loop9` looks like it's not unmapping loopdevices after use properly anymore – that's a quite high loop number. Or are you having a lot of loops mapped to other stuff before running it?

**Comment by zvin** [comment]
That's a bug that I've already fixed in the upcoming "integrate with resin-cli" PR.
It is due to an `exit(1)` in the code preventing the context manager from removing the loop device when an error happens: https://github.com/resin-io/resin-preload/blob/master/src/preload.py#L224

**Comment by zvin** [comment]
That said this is not the cause of the mount error as it worked on the next try.

**Comment by lurch** [comment]
Is it possible that `/tmp` had got full up, and `/tmp/tmphaofl9n9/opt/resin-image-ts4900.resinos-img` couldn't be created? Or is that condition already checked for?

**Comment by zvin** [comment]
@lurch this file is not created, it is already in the image.
This issue is quite old and the code has changed since, I'm considering closing it.

**Comment by lurch** [comment]
> @lurch this file is not created, it is already in the image.

Ahhh, didn't realise that ;-)  Still, it might be worth checking that `/tmp/tmphaofl9n9/opt/resin-image-ts4900.resinos-img` actually exists, so that if this error happens again you could display a more "friendly" error message, rather than the big stacktrace caused by the `mount` command failing? \*shrug\*
